##############################################################
##########LinYan Word -林言综合信息插件 QQ:1223233300#########
##############################################################
#添加颜色请使用“ § ” ， 而不是 “ & ”

############################################
##########关  键  词  屏  蔽  设  置########
############################################
badword:
  #是否开启关键词屏蔽
  enable: true
  #这里修改或者添加需要屏蔽的关键词
  word:
    - 'nmsl'
    - 'nmzl'
    - 'cnm'
  #这里设置自定义屏蔽后发送的文本
  setmessage: "§c喵喵喵???"
  #屏蔽脏话后发送标题
  message:
    title: "§e§L[§C§L提示§e§L]"
    subtitle: "§7§L服务器里不允许说脏话哦!"
  #发送脏话后弹出标题
  bypass:
    title: "§e§L[§C§L咦惹§e§L]"
    subtitle: "§7§L你竟然说脏话了!"
  #是否开启惩罚
  chengfa: false
  #惩罚指令
  command: "kill %player%"

############################################
#######玩  家  进  退  提  示  设  置#######
############################################
jl:
  #是否开启进退提示
  enable: true
  #进入提示
  join: "§e[§a+§e]§f %player%加入了游戏"
  #退出提示
  leave: "§e[§a-§e]§f %player%退出了游戏"

############################################
#######喊  话  美  化  显  示  设  置#######
############################################
notice:
  #公告空格请用 %% 代替, 例如 [a 1] 的格式为 [a%%1]
  #上边栏
  up: "§d================================================="
  #下边栏
  down: "§d================================================="
  #所有人都能看见的Title
  title: "§b§l§m--|[§e§l有新消息§b§l§m]|--"
  subtitle: "§b§l %player% §f§l发送了新的消息!"
############################################
#######清  屏  底  部  显  示  设  置#######
############################################
clear:
  #清屏信息
  message: "&b&L已经为全体玩家清屏 :)"
